apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Auth Service Postgres
  AUTH_SERVICE_POSTGRES_DB: auth-postgres
  AUTH_SERVICE_POSTGRES_USER: auth-postgres
  AUTH_SERVICE_POSTGRES_PASSWORD: auth-postgres
  AUTH_SERVICE_POSTGRES_HOST: auth-service-db
  AUTH_SERVICE_POSTGRES_PORT: "5432"

  # Auth Service Kafka
  AUTH_SERVICE_KAFKA_HOST: kafka-auth
  AUTH_SERVICE_KAFKA_PORT: "9092"

  # Secret key for services
  SECRET_KEY: innowise-intern-auth-service-innowise-intern-auth-service

  # User Service Redis
  USER_SERVICE_REDIS_HOST: user-service-redis
  USER_SERVICE_REDIS_PORT: "6379"
  USER_SERVICE_REDIS_PASSWORD: user-redis

  # User Service Postgres
  USER_SERVICE_POSTGRES_HOST: user-service-db
  USER_SERVICE_POSTGRES_PORT: "5432"
  USER_SERVICE_POSTGRES_DB: user-postgres
  USER_SERVICE_POSTGRES_USER: user-postgres
  USER_SERVICE_POSTGRES_PASSWORD: user-postgres

  # Order Service Postgres
  ORDER_SERVICE_POSTGRES_HOST: order-service-db
  ORDER_SERVICE_POSTGRES_PORT: "5432"
  ORDER_SERVICE_POSTGRES_DB: order-postgres
  ORDER_SERVICE_POSTGRES_USER: order-postgres
  ORDER_SERVICE_POSTGRES_PASSWORD: order-postgres

  # Payment Service Mongo
  PAYMENT_MONGO_HOST: mongo-db
  PAYMENT_MONGO_PORT: "27017"
  PAYMENT_MONGO_DB: payment_db
  PAYMENT_MONGO_USERNAME: payment_user
  PAYMENT_MONGO_PASSWORD: payment_pass
